export type Template = {
  slug: string;
  industry: string;
  benefit: string;
  url: string;
  brand: string;
  tagline: string;
  headline: string;
  subline: string;
  phone: string | null;
  services: { label: string; detail: string; price?: string }[];
  cta: string;
  secondaryCta: string;
  bg: string;
  accent: string;
  imageBg: string;
  badge: string | null;
  hours: string | null;
  trust: string[];
  about: string;
  address: string;
  email: string;
  image?: string;
  image2?: string;
  image3?: string;
};

export const templates: Template[] = [
  {
    slug: "installateur",
    industry: "Installateur & Handwerker",
    benefit: "Notfallnummer prominent, Leistungen klar, Anfrage in Sekunden.",
    url: "huber-sanitaer.at",
    brand: "Huber Sanitär",
    tagline: "Heizung · Sanitär · Notdienst",
    headline: "Schnell. Zuverlässig. Vor Ort.",
    subline: "Installationen, Wartung und 24h-Notdienst für Wien und Umgebung.",
    phone: "+43 1 234 5678",
    services: [
      { label: "Heizungsservice", detail: "Wartung, Reparatur und Austausch aller gängigen Heizsysteme — Gas, Wärmepumpe, Solar.", price: "Kostenloser Kostenvoranschlag" },
      { label: "Sanitärinstallation", detail: "Komplette Badezimmer-Umbauten, Küche, WC-Anlagen und Rohrarbeiten.", price: "Festpreisangebot" },
      { label: "Notdienst 24/7", detail: "Rohrbruch, Heizungsausfall, Verstopfung — wir sind auch am Wochenende erreichbar.", price: "Sofort verfügbar" },
    ],
    cta: "Jetzt anrufen",
    secondaryCta: "Anfrage senden",
    bg: "#192840",
    accent: "#D4500A",
    imageBg: "#253A55",
    badge: "24h Notdienst",
    hours: "Mo–Fr  7:00–17:00  ·  Notdienst 24/7",
    trust: ["Meisterbetrieb", "Wien & Niederösterreich", "Seit 1994"],
    about: "Huber Sanitär ist ein familiengeführter Meisterbetrieb mit über 30 Jahren Erfahrung in Wien und Niederösterreich. Wir arbeiten schnell, sauber und zuverlässig — mit klaren Preisen und ohne Überraschungen auf der Rechnung.",
    address: "Mariahilfer Straße 88, 1060 Wien",
    email: "office@huber-sanitaer.at",
  },
  {
    slug: "reinigung",
    industry: "Reinigung & Gebäudeservice",
    benefit: "Vertrauen auf den ersten Blick — Leistungen, Erfahrung, Anfrageformular.",
    url: "sauber-co.at",
    brand: "Sauber & Co.",
    tagline: "Büro · Haushalt · Umzugsreinigung",
    headline: "Sauberkeit, auf die Sie sich verlassen",
    subline: "Professionelle Reinigungsdienstleistungen für Betriebe und Privatkunden.",
    phone: "+43 664 123 4567",
    services: [
      { label: "Büroreinigung", detail: "Regelmäßige Reinigung von Büros, Praxen und Gewerbeflächen — täglich, wöchentlich oder nach Bedarf.", price: "Ab 3,90€/m²" },
      { label: "Fensterreinigung", detail: "Professionelle Reinigung innen und außen, auch für schwer erreichbare Bereiche.", price: "Auf Anfrage" },
      { label: "Umzugsreinigung", detail: "Besenrein-Übergabe, Endreinigung und Grundreinigung nach Umbau oder Auszug.", price: "Pauschalpreis" },
    ],
    cta: "Angebot anfordern",
    secondaryCta: "Alle Leistungen",
    bg: "#163B2A",
    accent: "#28A060",
    imageBg: "#1E5038",
    badge: "15 Jahre Erfahrung",
    hours: "Mo–Fr  7:00–17:00",
    trust: ["Versichert & zertifiziert", "Wien & Umgebung", "15 Jahre Erfahrung"],
    about: "Sauber & Co. steht seit 2009 für verlässliche, professionelle Reinigungsdienstleistungen. Unser Team aus geschulten Fachkräften arbeitet diskret, pünktlich und gründlich — mit eigenem Equipment und umweltschonenden Reinigungsmitteln.",
    address: "Favoritenstraße 55, 1040 Wien",
    email: "office@sauber-co.at",
  },
  {
    slug: "fahrradladen",
    industry: "Fahrradladen",
    benefit: "Sortiment, Werkstatttermine und Öffnungszeiten digital erreichbar.",
    url: "rad-und-tat.at",
    brand: "Rad & Tat",
    tagline: "Verkauf · Werkstatt · E-Bikes",
    headline: "Ihr Fahrrad in besten Händen",
    subline: "Verkauf, Service und Reparatur für alle Fahrradtypen — E-Bikes, City, Rennrad.",
    phone: null,
    services: [
      { label: "E-Bikes & Räder", detail: "Große Auswahl an E-Bikes, City- und Trekkingradern — von Einsteiger bis Premium.", price: "Ab 599€" },
      { label: "Werkstatt & Service", detail: "Inspektion, Bremsenwechsel, Schaltungseinstellung — Termin einfach online buchen.", price: "Ab 39€" },
      { label: "Zubehör & Ersatzteile", detail: "Helme, Schlösser, Beleuchtung und Ersatzteile für alle Marken — großes Lager.", price: "Immer verfügbar" },
    ],
    cta: "Werkstatttermin",
    secondaryCta: "Sortiment ansehen",
    bg: "#1A2B1A",
    accent: "#3D8B3D",
    imageBg: "#243C24",
    badge: null,
    hours: "Di–Fr  9:00–18:00  ·  Sa  9:00–14:00",
    trust: ["Fachhandel seit 1998", "Wien, 15. Bezirk", "Alle Marken"],
    about: "Rad & Tat ist seit 1998 der Fachhandel für Fahrräder im 15. Bezirk. Wir beraten ehrlich, reparieren schnell und führen nur Qualität, hinter der wir stehen. Bei uns kauft man nicht anonym — wir kennen unsere Kunden und ihr Rad.",
    address: "Hütteldorfer Straße 18, 1150 Wien",
    email: "hallo@rad-und-tat.at",
  },
  {
    slug: "kosmetikstudio",
    industry: "Kosmetikstudio",
    benefit: "Online-Buchung, Behandlungsübersicht und Preisliste auf einen Blick.",
    url: "studio-lumiere.at",
    brand: "Studio Lumière",
    tagline: "Kosmetik · Nails · Massage",
    headline: "Schönheit mit Sorgfalt",
    subline: "Individuelle Behandlungen in ruhiger Atmosphäre — nach Terminvereinbarung.",
    phone: "+43 676 987 6543",
    services: [
      { label: "Gesichtsbehandlung", detail: "Individuell abgestimmte Gesichtspflege mit hochwertigen Produkten — für jeden Hauttyp.", price: "Ab 55€ · 60 Min." },
      { label: "Naildesign", detail: "Gel, Acryl und natürliche Nagelpflege — inkl. Gestaltung nach Ihren Wünschen.", price: "Ab 35€" },
      { label: "Massagen", detail: "Entspannende Rücken- und Ganzkörpermassagen zur Erholung und Entspannung.", price: "Ab 49€ · 45 Min." },
    ],
    cta: "Termin buchen",
    secondaryCta: "Preisliste ansehen",
    bg: "#2E1E1E",
    accent: "#9B6060",
    imageBg: "#4A2E2E",
    badge: null,
    hours: "Di–Sa nach Terminvereinbarung",
    trust: ["Zertifizierte Kosmetikerin", "Wien, 1080", "Seit 2014"],
    about: "Studio Lumière bietet professionelle Kosmetik- und Wellnessbehandlungen in einer ruhigen, persönlichen Atmosphäre. Inhaberin Marie arbeitet ausschließlich mit zertifizierten Produkten und nimmt sich für jeden Kunden die Zeit, die er verdient.",
    address: "Josefstädter Straße 22, 1080 Wien",
    email: "marie@studio-lumiere.at",
  },
  {
    slug: "arztpraxis",
    industry: "Arztpraxis",
    benefit: "Sprechzeiten, Fachrichtung und Online-Termin klar und sofort sichtbar.",
    url: "praxis-dr-mayer.at",
    brand: "Dr. med. Mayer",
    tagline: "Allgemeinmedizin · Hausarzt",
    headline: "Ihre Hausarztpraxis in Wien",
    subline: "Persönliche Betreuung, kurze Wartezeiten und Online-Terminbuchung.",
    phone: "+43 1 876 5432",
    services: [
      { label: "Allgemeinmedizin", detail: "Behandlung akuter und chronischer Erkrankungen, Überweisungen und Rezepte — Kasse & Privat.", price: "Kassenvertrag" },
      { label: "Vorsorgeuntersuchung", detail: "Jährliche Gesundenuntersuchung inkl. Blutbild, EKG und ausführlichem Beratungsgespräch.", price: "Kostenfrei mit Kasse" },
      { label: "Online Terminbuchung", detail: "Terminvereinbarung rund um die Uhr über unsere Website — schnell und unkompliziert.", price: "24h verfügbar" },
    ],
    cta: "Termin vereinbaren",
    secondaryCta: "Sprechzeiten",
    bg: "#132238",
    accent: "#1A6BB5",
    imageBg: "#1E3A5F",
    badge: "Kasse & Privat",
    hours: "Mo Di Do  8:00–12:00 & 14:00–17:00  ·  Fr  8:00–12:00",
    trust: ["Seit 2005 in Wien", "Barrierefreier Zugang", "Alle Kassen"],
    about: "Dr. med. Thomas Mayer führt seit 2005 seine Hausarztpraxis im 3. Bezirk. Wir legen Wert auf persönliche Betreuung und kurze Wartezeiten. Online-Terminbuchung macht es einfach, einen Termin zu finden — auch außerhalb der Öffnungszeiten.",
    address: "Landstraßer Hauptstraße 14, 1030 Wien",
    email: "praxis@dr-mayer.at",
  },
  {
    slug: "dachdecker",
    industry: "Dachdecker & Bau",
    benefit: "Leistungen, Referenzfotos und kostenlose Beratung sofort buchbar.",
    url: "dach-und-fach.at",
    brand: "Dach & Fach GmbH",
    tagline: "Flachdach · Steildach · Klempner",
    headline: "Ihr Dach in sicheren Händen",
    subline: "Qualitätsarbeit auf jedem Dach — Neubau, Sanierung, Reparatur, Klempner.",
    phone: "+43 676 555 0123",
    services: [
      { label: "Flachdachsanierung", detail: "Professionelle Sanierung und Abdichtung von Flachdächern — dauerhaft dicht, auch bei Extremwetter.", price: "Kostenloses Angebot" },
      { label: "Steildachdeckung", detail: "Neueindeckung und Sanierung mit Ziegel, Schiefer, Bitumen oder Blech nach Wahl.", price: "Festpreis möglich" },
      { label: "Klempnerarbeiten", detail: "Dachrinnen, Fallrohre, Blecharbeiten und alle Abdichtungsarbeiten am Dach.", price: "Ab 280€" },
    ],
    cta: "Kostenlose Beratung",
    secondaryCta: "Referenzen ansehen",
    bg: "#221208",
    accent: "#A84010",
    imageBg: "#3A2010",
    badge: "Kostenloser Kostenvoranschlag",
    hours: "Mo–Fr  7:00–16:00",
    trust: ["Meisterbetrieb", "Wien & Umgebung", "Seit 2001"],
    about: "Dach & Fach GmbH ist ein zugelassener Meisterbetrieb für Dachdeckerarbeiten und Klempnerei in Wien und Umgebung. Gegründet 2001, stehen wir für solide Handwerksarbeit, transparente Preise und termintreue Ausführung — auch bei komplexen Projekten.",
    address: "Gewerbepark 7, 1230 Wien",
    email: "office@dach-und-fach.at",
  },
  {
    slug: "lokales-geschaeft",
    industry: "Lokales Geschäft",
    benefit: "Sortiment zeigen, Öffnungszeiten klar — mehr Laufkundschaft online.",
    url: "stadtladen-wien.at",
    brand: "Stadtladen Wien",
    tagline: "Regionales · Lebensmittel · Geschenke",
    headline: "Qualität aus der Nachbarschaft",
    subline: "Regionale Produkte, frische Waren und liebevoll zusammengestellte Geschenkkörbe.",
    phone: "+43 1 555 7890",
    services: [
      { label: "Regionale Produkte", detail: "Täglich frische Lieferungen von Wiener und niederösterreichischen Produzenten — Käse, Wurst, Backwaren.", price: "Immer frisch" },
      { label: "Geschenkkörbe", detail: "Individuell zusammengestellte Geschenkkörbe für jeden Anlass — auch auf Bestellung.", price: "Ab 35€" },
      { label: "Lieferservice Wien", detail: "Wir liefern Ihre Bestellung direkt nach Hause — innerhalb Wiens ab einem Bestellwert von 25€.", price: "Ab 25€ kostenlos" },
    ],
    cta: "Zum Sortiment",
    secondaryCta: "Öffnungszeiten",
    bg: "#211A0A",
    accent: "#7A5A1E",
    imageBg: "#3A2E10",
    badge: null,
    hours: "Mo–Fr  9:00–19:00  ·  Sa  9:00–17:00",
    trust: ["Familienbetrieb seit 1987", "Wien, 1060", "Regional & fair"],
    about: "Der Stadtladen Wien ist seit 1987 in Familienbesitz. Wir führen ausschließlich Produkte, hinter denen wir stehen — von kleinen Betrieben aus Wien und Niederösterreich. Unser Ziel: Qualität, die man schmeckt, von Menschen, die man kennt.",
    address: "Gumpendorfer Straße 31, 1060 Wien",
    email: "hallo@stadtladen-wien.at",
  },
  {
    slug: "baeckerei",
    industry: "Bäckerei",
    benefit: "Frisches Brot, Öffnungszeiten und Bestellung — einfach online.",
    url: "brotzeit-vienna.at",
    brand: "Brotzeit Bakery Vienna",
    tagline: "Sauerteig · Handwerk · Wien",
    headline: "Handgemacht. Täglich frisch.",
    subline: "Echtes Handwerk, ehrliche Zutaten — Brot und Gebäck wie früher, mitten in Wien.",
    phone: "+43 1 890 1234",
    services: [
      { label: "Sauerteigbrot", detail: "Täglich frisch gebacken — Roggen, Weizen, Dinkel und Mehrkorn in kleinen Chargen.", price: "Ab 4,80€" },
      { label: "Feingebäck & Kuchen", detail: "Croissants, Kipferl, Nussschnecken und saisonale Spezialitäten — jeden Morgen frisch.", price: "Ab 1,60€" },
      { label: "Bestellung & Catering", detail: "Brotplatten, Frühstücksboxen und individuelle Bestellungen für Events und Büros.", price: "Auf Anfrage" },
    ],
    cta: "Jetzt bestellen",
    secondaryCta: "Sortiment ansehen",
    bg: "#1C1208",
    accent: "#A0622A",
    imageBg: "#3D2210",
    badge: null,
    hours: "Mo–Fr  6:30–18:00  ·  Sa  7:00–14:00",
    trust: ["Handwerk seit 2011", "Wien, 8. Bezirk", "Nur natürliche Zutaten"],
    about: "Brotzeit Bakery Vienna steht für echtes Bäckerhandwerk ohne Kompromisse. Jedes Brot wird mit langen Teigruhezeiten, natürlichem Sauerteig und regionalen Zutaten gebacken. Kein Backmittel, keine Fertigmischungen — nur Zeit, Technik und gute Rohstoffe.",
    address: "Josefstädter Straße 9, 1080 Wien",
    email: "hallo@brotzeit-vienna.at",
    image: "/images/templates/bakery.png",
    image2: "/images/templates/bakery-interior.png",
    image3: "/images/templates/bakery-pastries.png",
  },
];

export function getTemplateBySlug(slug: string): Template | undefined {
  return templates.find((t) => t.slug === slug);
}
